"""add enable_verify and verified_indices to jobs

Revision ID: a0fd54d5fe67
Revises: 2bb750402812
Create Date: 2026-03-25 15:22:09.008532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0fd54d5fe67'
down_revision: Union[str, None] = '2bb750402812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('enable_verify', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('jobs', sa.Column('verified_indices', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('verify_reasons', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'verify_reasons')
    op.drop_column('jobs', 'verified_indices')
    op.drop_column('jobs', 'enable_verify')
    # ### end Alembic commands ###
